# Generated by Django 4.0.4 on 2022-06-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
