# Generated by Django 4.0.4 on 2022-06-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Posteo',
        ),
    ]
