# Generated by Django 4.0.4 on 2022-06-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_perfil_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
