# Generated by Django 4.0.4 on 2022-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_mensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Perfiles',
        ),
        migrations.DeleteModel(
            name='Posteo',
        ),
    ]
