# Generated by Django 4.0.4 on 2022-06-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_posteos_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
