# Generated by Django 4.0.4 on 2022-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_delete_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
