# Generated by Django 4.0.4 on 2022-06-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_posteos_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posteos',
        ),
    ]
