# Generated by Django 4.0.4 on 2022-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_delete_posteos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
