# Generated by Django 4.0.4 on 2022-06-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_posteos_user_alter_posteos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteos',
            name='avatar',
        ),
    ]
