# Generated by Django 4.0.4 on 2022-06-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0023_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
